language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get install -y enchant
install:
  - pip install -r requirements/dev.txt
# command to run tests
script: 
  - bin/test.sh
  - bin/pylint_score_guard.sh